# Generated by Django 3.1 on 2020-08-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200820_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='earnings',
        ),
    ]
