# Generated by Django 3.1 on 2020-08-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200822_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='startingBid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
